---
title: "EM-algorithm example \\(a bivariate case)"
author: "Marc Comas-Cufí"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{EM-algorithm example \\(a bivariate case)}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r}
library(normalmultinomial)
set.seed(1)
```

Let's start fith the following distribution

```{r}
(mu <- c(0,2))
(Sigma <- matrix(c(1, -0.7,
                   -0.7, 2), nrow=2) * 10)
```

```{r, warning=F}
head(X <- rnormalmultinomial(mu = mu, sigma = Sigma, size = sample(20:80, 100, replace=T)))
```

### M-step

We start with an estimation of non-observable sample $A$.

```{r}
Xt = X
Xt[Xt == 0] = 0.66
A = log(Xt[,1:2]/Xt[,3])
```

With the observations $A$, we have the estimators

```{r}
(m_t0 <- apply(A, 2, mean))
(Sigma_t0 = cov(A))
```

### E-step

With the parameters `m_t`and `Sigma_t` estimated, we need to estimate $E_{A/(m\_t, sigma\_t)}\left[ a_i \right]$ and $E_{A/(m\_t, sigma\_t)} \left[ a_i^2 \right]$ for each $x_i$.

```{r}
# to test
# x = Xt[1,]
# m = m_t0
# inv_Sigma = solve(Sigma_t0)
# nsim = 100
moments_rnd = function(x, m, inv_Sigma, nsim=100){
  p = log(x[1:2]/x[3])
  Ap = matrix( c(runif(nsim, p[1]-5, p[1]+5),
                 runif(nsim, p[2]-5, p[2]+5)), ncol = 2)
  lik = exp(apply(Ap, 1, mvf, m, inv_Sigma, x))
  
  res_rnd = list('mean' = c(0,0), 'Sigma' = matrix(0, nrow=2, ncol=2))
  for(i in 1:2){
    res_rnd[['mean']][i] = mean(Ap[,i] * lik) / mean(lik)
    for(j in 1:2){
      res_rnd[['Sigma']][i,j] = mean(Ap[,i] * Ap[,j] * lik) / mean(lik)
    }
  }
  res_rnd
}

mom = t( apply(Xt, 1, moments_rnd, m_t0, solve(Sigma_t0), nsim = 1000) )

m_t <- Reduce(`+`, lapply(mom, function(pars) pars[[1]]))/nrow(X)
Sigma_t <- Reduce(`+`, lapply(mom, function(pars) pars[[2]])) / length(mom) - 
  t(matrix(m_t, nrow=1)) %*% matrix(m_t, nrow=1)
```


```{r}
nsteps = 20
res = matrix(0, ncol=6, nrow=nsteps)
for(i in 1:nsteps){
  mom = t( apply(Xt, 1, moments_rnd, m_t, solve(Sigma_t), nsim = 1000) )
  
  m_t <- Reduce(`+`, lapply(mom, function(pars) pars[[1]]))/nrow(X)
  Sigma_t <- Reduce(`+`, lapply(mom, function(pars) pars[[2]])) / length(mom) - 
    t(matrix(m_t, nrow=1)) %*% matrix(m_t, nrow=1)

  res[i,1] <- i
  res[i,2] <- m_t[1]
  res[i,3] <- m_t[2]
  res[i,4] <- Sigma_t[1,1]
  res[i,5] <- Sigma_t[2,2]
  res[i,6] <- Sigma_t[1,2]
}
colnames(res) = c('step', 'mean1', 'mean2', 'cov11', 'cov22', 'cov12')
data.frame( rbind( matrix(c(0, m_t0[1], m_t0[2], Sigma_t0[1,1], Sigma_t0[2,2], Sigma_t0[1,2]), nrow=1), res) )
```