# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvf_norm <- function(a, mu, inv_sigma) {
    .Call('normalmultinomial_mvf_norm', PACKAGE = 'normalmultinomial', a, mu, inv_sigma)
}

mvf_multinom_const <- function(x) {
    .Call('normalmultinomial_mvf_multinom_const', PACKAGE = 'normalmultinomial', x)
}

mvf_multinom_mult <- function(a, x) {
    .Call('normalmultinomial_mvf_multinom_mult', PACKAGE = 'normalmultinomial', a, x)
}

mvf_multinom <- function(a, x) {
    .Call('normalmultinomial_mvf_multinom', PACKAGE = 'normalmultinomial', a, x)
}

#' Finds the mean and covariance of a normal multinomial distribution
#'
#' @param a aln hidden obeservation
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @param x normal-multinomial observation
#' @return Loglikelihood og oberserved data
#' @export
mvf <- function(a, mu, inv_sigma, x) {
    .Call('normalmultinomial_mvf', PACKAGE = 'normalmultinomial', a, mu, inv_sigma, x)
}

#' Finds the mean and covariance of a normal multinomial distribution
#'
#' @param a aln hidden obeservation
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @param x normal-multinomial observation
#' @return Loglikelihood og oberserved data
#' @export
mvf_deriv <- function(I, a, mu, inv_sigma, x) {
    .Call('normalmultinomial_mvf_deriv', PACKAGE = 'normalmultinomial', I, a, mu, inv_sigma, x)
}

#' Finds the mean and covariance of a normal multinomial distribution
#'
#' @param a aln hidden obeservation
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @param x normal-multinomial observation
#' @return Loglikelihood og oberserved data
#' @export
mvf_deriv2 <- function(I, J, a, mu, inv_sigma, x) {
    .Call('normalmultinomial_mvf_deriv2', PACKAGE = 'normalmultinomial', I, J, a, mu, inv_sigma, x)
}

#' Evaluates the log-likelihood of thenormal multinomial distribution given the hidden observation
#'
#' @param X normal-multinomial observations
#' @param A aln non-observed obeservations
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @return Loglikelihood of the oberserved and non-observed data
#' @export
logLike <- function(X, A, mu, inv_sigma) {
    .Call('normalmultinomial_logLike', PACKAGE = 'normalmultinomial', X, A, mu, inv_sigma)
}

#' Returns the gaussian more like to generate a sample X given parameters mu and sigma
#'
#' @param A aln hidden obeservations
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @param X normal-multinomial observations
#' @return Loglikelihood oberserved data
#' @export
maximize_mvf <- function(mu, inv_sigma, X, eps = 1e-8, max_iter = 100L, prop = 0.66) {
    .Call('normalmultinomial_maximize_mvf', PACKAGE = 'normalmultinomial', mu, inv_sigma, X, eps, max_iter, prop)
}

#' Compute the mean and covariance of a normal multinomial distribution after itering an EM-algorithm
#'
#' @param X normal-multinomial sample
#' @param mu initial meean estimate
#' @param sigma initial covariance estimate
#' @param nsim number of repetitions for the montecarlo integration process
#' @param niter number of iteration
#' @export
EM_step <- function(X, mu, sigma, nsim = 1000L, niter = 1L) {
    .Call('normalmultinomial_EM_step', PACKAGE = 'normalmultinomial', X, mu, sigma, nsim, niter)
}

#' Compute the mean and covariance of a normal multinomial distribution after itering an EM-algorithm
#'
#' @param X normal-multinomial sample
#' @param mu initial meean estimate
#' @param sigma initial covariance estimate
#' @param nsim number of repetitions for the montecarlo integration process
#' @param niter number of iteration
#' @export
E_step1 <- function(X, mu, sigma, nsim = 1000L) {
    .Call('normalmultinomial_E_step1', PACKAGE = 'normalmultinomial', X, mu, sigma, nsim)
}

#' Compute the mean and covariance of a normal multinomial distribution after itering an EM-algorithm
#'
#' @param X normal-multinomial sample
#' @param mu initial meean estimate
#' @param sigma initial covariance estimate
#' @param nsim number of repetitions for the montecarlo integration process
#' @param niter number of iteration
#' @export
E_step2 <- function(X, mu, sigma, nsim = 1000L) {
    .Call('normalmultinomial_E_step2', PACKAGE = 'normalmultinomial', X, mu, sigma, nsim)
}

#' Compute the mean and covariance of a normal multinomial distribution after itering an EM-algorithm
#'
#' @param X normal-multinomial sample
#' @param mu initial meean estimate
#' @param sigma initial covariance estimate
#' @param nsim number of repetitions for the montecarlo integration process
#' @param niter number of iteration
#' @export
E_step3 <- function(X, mu, sigma, nsim = 1000L) {
    .Call('normalmultinomial_E_step3', PACKAGE = 'normalmultinomial', X, mu, sigma, nsim)
}

#' Compute the mean and covariance of a normal multinomial distribution after itering an EM-algorithm
#'
#' @param X normal-multinomial sample
#' @param mu initial meean estimate
#' @param sigma initial covariance estimate
#' @param nsim number of repetitions for the montecarlo integration process
#' @param niter number of iteration
#' @export
E_step4 <- function(X, mu, sigma, nsim = 1000L) {
    .Call('normalmultinomial_E_step4', PACKAGE = 'normalmultinomial', X, mu, sigma, nsim)
}

#' Finds the mean and covariance of a normal multinomial distribution
#'
#' @param X normal-multinomial sample
#' @param nsim number of repetitions for the montecarlo integration process
#' @param niter number of iterations for the EM-algorithm
#' @param prop first 0 imputation
#' @export
normalmultinomial_fitting <- function(X, nsim = 1000L, niter = 20L, prop = 0.66, version = 0L) {
    .Call('normalmultinomial_normalmultinomial_fitting', PACKAGE = 'normalmultinomial', X, nsim, niter, prop, version)
}

c_rnormal <- function(n, mu, sigma) {
    .Call('normalmultinomial_c_rnormal', PACKAGE = 'normalmultinomial', n, mu, sigma)
}

c_rmultinomial <- function(A, size, seed = 1L) {
    .Call('normalmultinomial_c_rmultinomial', PACKAGE = 'normalmultinomial', A, size, seed)
}

c_rnormalmultinomial <- function(mu, sigma, size, seed) {
    .Call('normalmultinomial_c_rnormalmultinomial', PACKAGE = 'normalmultinomial', mu, sigma, size, seed)
}

