# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate variables following a normal distribution. 
#' 
#' @param n sample size
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @return Sample matrix
#' @export
rnormal <- function(n, mu, sigma) {
    .Call('normalmultinomial_rnormal', PACKAGE = 'normalmultinomial', n, mu, sigma)
}

#' Simulate variables following a multinomial distribution. 
#' 
#' @param A matrix with the probabilities used to generate the sample
#' @param size vector with the countings in each row of A
#' @return sample with the same dimension as A
#' @export
rmultinomial <- function(A, size) {
    .Call('normalmultinomial_rmultinomial', PACKAGE = 'normalmultinomial', A, size)
}

#' Simulate variables following a normal multinomial distribution. 
#' 
#' @param n sample size
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @return Sample matrix
#' @export
rnormalmultinomial <- function(mu, sigma, size) {
    .Call('normalmultinomial_rnormalmultinomial', PACKAGE = 'normalmultinomial', mu, sigma, size)
}

#' Evaluates the log-likelihood of thenormal multinomial distribution given the hidden observation
#' 
#' @param X normal-multinomial observations
#' @param A aln non-observed obeservations
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @return Loglikelihood of the oberserved and non-observed data
#' @export
logLike <- function(X, A, mu, inv_sigma) {
    .Call('normalmultinomial_logLike', PACKAGE = 'normalmultinomial', X, A, mu, inv_sigma)
}

#' Compute the mean and covariance of a normal multinomial distribution after itering an EM-algorithm
#' 
#' @param X normal-multinomial sample
#' @param mu initial meean estimate
#' @param sigma initial covariance estimate
#' @param nsim number of repetitions for the montecarlo integration process
#' @param niter number of iteration
#' @export
EM_step <- function(X, mu, sigma, nsim = 1000L, niter = 1L) {
    .Call('normalmultinomial_EM_step', PACKAGE = 'normalmultinomial', X, mu, sigma, nsim, niter)
}

#' Finds the mean and covariance of a normal multinomial distribution
#' 
#' @param X normal-multinomial sample
#' @param nsim number of repetitions for the montecarlo integration process
#' @param niter number of iterations for the EM-algorithm
#' @param prop first 0 imputation
#' @export
normalmultinomial_fitting <- function(X, nsim = 1000L, niter = 20L, prop = 0.66) {
    .Call('normalmultinomial_normalmultinomial_fitting', PACKAGE = 'normalmultinomial', X, nsim, niter, prop)
}

