# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate variables following a normal distribution. 
#' 
#' @param n sample size
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @return Sample matrix
#' @export
rnormal <- function(n, mu, sigma) {
    .Call('normalmultinomial_rnormal', PACKAGE = 'normalmultinomial', n, mu, sigma)
}

#' Simulate variables following a multinomial distribution. 
#' 
#' @param A matrix with the probabilities used to generate the sample
#' @param size vector with the countings in each row of A
#' @return sample with the same dimension as A
#' @export
rmultinomial <- function(A, size) {
    .Call('normalmultinomial_rmultinomial', PACKAGE = 'normalmultinomial', A, size)
}

#' Simulate variables following a normal multinomial distribution. 
#' 
#' @param n sample size
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @return Sample matrix
#' @export
rnormalmultinomial <- function(mu, sigma, size) {
    .Call('normalmultinomial_rnormalmultinomial', PACKAGE = 'normalmultinomial', mu, sigma, size)
}

logLikelihood <- function(X, mu, sigma, N = 100L) {
    .Call('normalmultinomial_logLikelihood', PACKAGE = 'normalmultinomial', X, mu, sigma, N)
}

#' Finds the mean and covariance of a normal multinomial distribution
#' 
#' @param a aln hidden obeservation
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @param x normal-multinomial observation
#' @return Loglikelihood og oberserved data
#' @export
mvf <- function(a, mu, inv_sigma, x) {
    .Call('normalmultinomial_mvf', PACKAGE = 'normalmultinomial', a, mu, inv_sigma, x)
}

#' Finds the mean and covariance of a normal multinomial distribution
#' 
#' @param a aln hidden obeservation
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @param x normal-multinomial observation
#' @return Loglikelihood og oberserved data
#' @export
mvf_deriv <- function(I, a, mu, inv_sigma, x) {
    .Call('normalmultinomial_mvf_deriv', PACKAGE = 'normalmultinomial', I, a, mu, inv_sigma, x)
}

#' Finds the mean and covariance of a normal multinomial distribution
#' 
#' @param a aln hidden obeservation
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @param x normal-multinomial observation
#' @return Loglikelihood og oberserved data
#' @export
mvf_deriv2 <- function(I, J, a, mu, inv_sigma, x) {
    .Call('normalmultinomial_mvf_deriv2', PACKAGE = 'normalmultinomial', I, J, a, mu, inv_sigma, x)
}

#' Finds the mean and covariance of a normal multinomial distribution
#' 
#' @param A aln hidden obeservations
#' @param mu mean parameter for the mean in a aln-normal distribution
#' @param sigma parameter for the sigma in a aln-normal distribution
#' @param X normal-multinomial observations
#' @return Loglikelihood oberserved data
#' @export
#' 
Mstep <- function(A, mu, inv_sigma, X, eps = 1e-8, max_iter = 100L) {
    .Call('normalmultinomial_Mstep', PACKAGE = 'normalmultinomial', A, mu, inv_sigma, X, eps, max_iter)
}

#' Finds the mean and covariance of a normal multinomial distribution
#' 
#' @param X normal-multinomial sample
#' @param A initial values
#' @export
adjustNormalMultinomial_internal <- function(X, A, eps = 1e-04, iter = 100L, minSigma = 1e-06) {
    .Call('normalmultinomial_adjustNormalMultinomial_internal', PACKAGE = 'normalmultinomial', X, A, eps, iter, minSigma)
}

#' Finds the mean and covariance of a normal multinomial distribution
#' 
#' @param X normal-multinomial sample
#' @export
adjustNormalMultinomial <- function(X, eps = 1e-15, iter = 100L, prop = 0.3, minSigma = 1e-5) {
    .Call('normalmultinomial_adjustNormalMultinomial', PACKAGE = 'normalmultinomial', X, eps, iter, prop, minSigma)
}

